### ISSUE TITLE
Add bluetooth adaptor

### ISSUE THREAD

**Issue by guangbochen** [cnrancher/octopus#13]
Description:
Add Bluetooth adaptor that enables the user to connect to the BLE(Bluetooth low energy) devices.
```
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: xiaomi-temp-rs2200
spec:
  adaptor:
    node: ubuntu
    name: adaptors.edge.cattle.io/ble
    parameters:
      syncInterval: 30
      timeout: 60
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "BluetoothDevice"
  template:
    metadata:
      labels:
        device: xiaomi-temp-rs2200
    spec:
      name: "MJ_HT_V1"
      # macAddress: ""
      properties:
      - name: data
        description: XiaoMi temp sensor with temperature and humidity data
        accessMode: NotifyOnly
        visitor:
          characteristicUUID: 226c000064764566756266734470666d
      - name: humidity
        description: Humidity in percent
        accessMode: ReadOnly
        visitor:
          characteristicUUID: f000aa0304514000b000000000000000
          # dataConverter is optional
          dataConverter:
            startIndex: 1
            endIndex: 0
            shiftRight: 2
            orderOfOperations:
            - operationType: Multiply # options are Add/Subtract/Multiply/Divide
              operationValue: "0.03125"
      - name: power-enabled
        description: turn the device power on or off
        accessMode: ReadWrite
        visitor:
          # characteristicUUID, dataWrite and defaultValue is required when accessMode is ReadWrite
          characteristicUUID: f000aa0104514000b000000000000001
          defaultValue: OFF # set the defaultValue by chosen one of option in the dataWrite
          dataWrite:
            ON: [1]
            OFF: [0]
          # dataConverter is optional
          dataConverter:
            startIndex: 1
            endIndex: 0
            shiftRight: 3
            orderOfOperations:
            - operationType: Multiply
              operationValue: "0.03125"

```
