### ISSUE TITLE
reform device status property to a standarized object

### ISSUE THREAD

**Issue by guangbochen** [cnrancher/octopus#40]
**Description:**
the current data of status.properties of each device is different, we need to define a common object of the status property since they all used for displaying the device reported data.

**Solution:**
use the property object as below:
1. 
```YAML
status:
    properties:
    - dataType: float #string type
      name: temperature #string
      value: "24.1" # string
      updatedAt: "2020-04-03T05:08:46Z" # date
```
2. add an annotation to the device CRD to describe what values should be displayed for the status.property, e.g,
```YAML
  devices.edge.cattle.io/status-property: '{"name":"string","dataType":"string","value":"string","updatedAt":"date"}'

```
