### ISSUE TITLE
add catalog controller & MQTT management

### ISSUE THREAD

**Issue by guangbochen** [cnrancher/octopus#46]
**Description:**
Background: users should be able to add either local or remote chart library to the k3s cluster and install them using helmchart config(check the example as below), users with the air-gapped environment should be able to configure and enable local helm chart library that provided by the edge.
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: my-mqtt
  namespace: kube-system
spec:
  chart: emqx
  repo: https://chartmeseum.$namespace:80 # local hosted chart library
  targetNamespace: default
```

***Add Catalog controller***
1. allows user to enable helm library(i.e https://github.com/helm/chartmuseum) in the edge UI
    - user should be able to upload a helm chart and store it in the k3s local storage
    - user should be able to config to use other storage option like s3-compatible storage service
2. allows user to list/view catalog apps from the local library
3. allows users to deploy catalogs apps using k3s helmchart CRD.
4. allows user to manage/upgrade and delete catalog apps

***Add MQTT chart***
Add a curated collection of MQTT chart(i.e https://github.com/cnrancher/mqtt-charts) to the MQTT menu
